# Generated by Django 6.0.3 on 2026-03-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_coordenador',
            field=models.BooleanField(default=False, verbose_name='coordenador'),
        ),
    ]
