# Generated by Django 6.0.3 on 2026-04-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0002_usuario_is_coordenador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
